name: Create Python release windows macos

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching wonnx-py-v*
jobs:
  build:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-01-01
          override: true
          components: rustfmt, clippy
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin==0.12.1
      - name: Publish wheel
        shell: bash
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
        run: |
          cd wonnx-py
          rustup override set nightly-2022-01-01
          export RUSTFLAGS='-C target-feature=+fxsr,+sse,+sse2,+sse3'
          maturin publish \
          --no-sdist \
          --skip-existing \
          -o wheels \
          -i python \
          --username __token__ \
